# Generated by Django 3.0.5 on 2020-06-30 04:29

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0003_elementimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='elementimages',
            name='base_cover_ext',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='elementimages',
            name='base_cover_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='elementimages',
            name='cover',
            field=stdimage.models.JPEGField(upload_to='images/'),
        ),
    ]
