# Generated by Django 3.0.5 on 2020-05-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
