# Generated by Django 3.0.5 on 2020-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_typecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='documento',
            field=models.FileField(default='', null=True, upload_to='uploads/contact'),
        ),
    ]
