# Generated by Django 3.0.5 on 2020-05-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200520_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero no especificar')], default='M', max_length=1),
        ),
    ]
