"""
Django settings for djangovue project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0avqio(yruqn^+jc#6j7yg$=q5f5-&q5l7gabnbym6og0sww$c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# LOGGING DEBUG

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers':{
        'console':{
            'class': 'logging.StreamHandler',
        },
        'file':{
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log'
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


ALLOWED_HOSTS =  [
    'testdjango.com','localhost','127.0.0.1'
]

# configuramos los mddleware para habilitar los peticiones de sitios cruzados
CORS_ORIGIN_ALLOW_ALL = True
# para evitar ataques, agregar a una lista blanca:
CORS_ORIGIN_WHITELIST = [
    "http://localhost:8080",
]

# Application definition
# referenciamos la app listelement
# referenciamos rest de django
# referenciamos cors de django
# definir account primero, ya que ahí yace el html de password_change_form antes del admin para que lo tome

INSTALLED_APPS = [
    'store',
    'account',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'debug_toolbar',
    'rest_framework',
    'corsheaders',
    'easy_thumbnails',
    'bootstrapform',
    'import_export',
    'widget_tweaks',
    'listelement',
    'restmanual',
    'comment',
    'taggit',
    'django_extensions',
    'social_django',
]

# referenciamos cors y common middleware para escuchar los responses
# colocar 'django.middleware.locale.LocaleMiddleware', antes de de CommonMiddleware, esto toma lenguaje del request (español)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    #'django.middleware.common.CommonMiddleware' no influye
]

# PAGINACIÓN PARA EL REST
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}


ROOT_URLCONF = 'djangovue.urls'

# Agregamos 'django.template.context_processors.media' que viene con el MEDIA_ROOT
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangovue.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# CONEXION A LA BASE DE DATOS MYSQL
# UTILIZANDO pip install mysqlclient

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'sql_mode': 'traditional'
        },
        'NAME': 'django_seccion_4',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# FIN CONEXION A BASE DE DATOS MYSQL

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Personalizacion de autenticación
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # registramos backend personalizado desde account authentication.copy()
    'account.authentication.AuthByEmailBackend',
    # ingresamos el social authentications que queramos para loguearnos
    # Google OAuth2
    'social_core.backends.google.GoogleOAuth2',
    # Twitter OAuth
    'social_core.backends.twitter.TwitterOAuth',
    # Facebook OAuth2
    'social_core.backends.facebook.FacebookOAuth2',
]

# Social Authentications
# Google https://testdjango.com:8000/social-auth/complete/google/
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '49067890108-u88i93m4p7s1007pjdu3ui37rdj3gdcf.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'YPKfo3qFfpaIfXr0-trLkeyW'
# Twitter https://testdjango.com:8000/social-auth/complete/twitter/
SOCIAL_AUTH_TWITTER_KEY = 'Gbk0AOZf6PT1wDvAaaiosfw4w'
SOCIAL_AUTH_TWITTER_SECRET = 'SF59n5zTX6GXVGt48a7UvMXSsDP9FZdr0cyGr0TmfrTeMbHBbz' 
# Facebook https://testdjango.com:8000/social-auth/complete/facebook/
SOCIAL_AUTH_FACEBOOK_KEY = '338952707498548'
SOCIAL_AUTH_FACEBOOK_SECRET = '4dab2d0d1a376abf00cfa88d9b0ab81a'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

# En caso de necesitar un namespace customizado
# SOCIAL_AUTH_URL_NAMESPACE = 'social'


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# Idioma, por defecto 'en-us'
LANGUAGE_CODE = 'es-ES'

# Localización de archivos para traducción de apps
LOCALE_PATHS = [
    os.path.join(BASE_DIR,'locale')
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# MEDIA_ROOT PARA AVATAR
MEDIA_ROOT = os.path.join(BASE_DIR,'uploads')
# MEDIA_URL PARA GENERALIZAR LA CARPETA DONDE VAN LAS SUBIDAS
MEDIA_URL = '/uploads/'

# CAMBIAR EL REDIRECT DEL LOGOUT
LOGOUT_REDIRECT_URL= '/accounts/login/'

# PRUEBAS CON MAILTRAP.IO PARA ENVIOS SMTP
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'c346f7be2bccb7'
EMAIL_HOST_PASSWORD = '79e1d2a217a5b9'
EMAIL_PORT = '2525'


# Paquete Easy Thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (100, 100), 'crop': True},
    },
}

# Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

# fin debug toolbar


# configuracion paypal general
PAYPAL_CLIENT_ID = "AfonCxpkyDoPGF79wsBxcBXzcYu0nlJ3FqBqzIFUgmgXkme5IdKK31YrfOldeCm8XOb3gAhe-ZU3ra41"
PAYPAL_CLIENT_SECRET = "EO-jMv4fMSbtlucnMj_awzQ--r8EBawCqpRfp4sHdeFlczY-5aqXtxxC2hxrSPZaFWm7j3D3-vS_BJWb"
PAYPAL_CLIENT_MODO = "sandbox" # sandbox or live


